Fix docker-image-size to work with podman

diff --git a/bin/docker-image-size b/bin/docker-image-size
--- a/bin/docker-image-size
+++ b/bin/docker-image-size
@@ -1,3 +1,14 @@
 #!/usr/bin/env bash
 
-docker inspect "$1" | jq '.[].Size' | numfmt --to=iec
+set -eo pipefail
+
+image="$1"
+
+if command -v docker > /dev/null; then
+  docker inspect "$image" | jq '.[].Size' | numfmt --to=iec
+elif command -v podman > /dev/null; then
+  podman inspect "$image" | jq '.[].Size' | numfmt --to=iec
+else
+  echo "Docker and Podman both not found!"
+  exit 1
+fi
